In [1]:
#import package for working with csv files
import pandas as pd
#import numpy for numeric computing 
import numpy as np
#import package for ploting + visualisations 
import matplotlib.pyplot as plt

In [2]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.
You should consider upgrading via the 'C:\Users\Rache\AppData\Local\Programs\Python\Python38-32\python.exe -m pip install --upgrade pip' command.


In [3]:
#read data from file and save in variable df.
df = pd.read_csv(r'C:\Users\Rache\OneDrive\Documents\comp30670SE\Andrewsorigdata.csv')

In [4]:
df.shape

(531860, 14)

In [5]:
df.head()

number  available_bike_stands  available_bikes  weather_id weather_main  \
0       2                     13                7         802       Clouds   
1       2                     12                8         802       Clouds   
2       2                     12                8         802       Clouds   
3       2                     13                7         802       Clouds   
4       2                     13                7         802       Clouds   

   main_temp  main_feels_like  main_temp_max  main_temp_min  main_pressure  \
0     284.35           280.55         284.82         283.71           1030   
1     284.44           280.65         284.82         283.71           1030   
2     284.35           280.55         284.82         283.71           1030   
3     284.44           280.65         284.82         283.71           1030   
4     284.35           280.55         284.82         283.71           1030   

   main_humidity  wind_speed                dt             test1  
0             62         3.6  21/03/2021 14:20  21/03/2021 14:15  
1             62         3.6  21/03/2021 14:35  21/03/2021 14:30  
2             62         3.6  21/03/2021 14:26  21/03/2021 14:30  
3             62         3.6  21/03/2021 14:35  21/03/2021 14:30  
4             62         3.6  21/03/2021 14:26  21/03/2021 14:30

In [6]:
dfj =df.sample(frac=1).reset_index(drop=True)

In [7]:
dfj.head()

number  available_bike_stands  available_bikes  weather_id weather_main  \
0      56                     29               11         803       Clouds   
1      58                     29               11         803       Clouds   
2      19                     23                7         803       Clouds   
3      61                     18                7         800        Clear   
4      53                     37                3         803       Clouds   

   main_temp  main_feels_like  main_temp_max  main_temp_min  main_pressure  \
0     286.34           281.03         286.48         285.93           1009   
1     280.78           274.91         281.15         280.15           1034   
2     281.16           278.41         282.04         280.15           1026   
3     280.22           276.22         280.93         278.71           1013   
4     278.85           275.54         279.26         278.15           1032   

   main_humidity  wind_speed                dt             test1  
0             82        7.72  28/03/2021 18:35  28/03/2021 18:30  
1             71        6.17  02/04/2021 12:13  02/04/2021 12:15  
2             76        2.06  22/03/2021 05:29  22/03/2021 05:30  
3             87        4.12  25/03/2021 04:18  25/03/2021 04:15  
4             81        4.63  02/04/2021 07:18  02/04/2021 07:15

In [8]:
dfj.shape


(531860, 14)

In [9]:
#2 thirds saved for trinaing data
dftrain=dfj.iloc[1:354573, 0:14]


In [10]:
dftrain.shape


(354572, 14)

In [11]:

#one third saved for testing 
dftest=dfj.iloc[354573:531860, 0:14]

In [12]:
dftest.shape

(177287, 14)

In [13]:
dftest.head()


number  available_bike_stands  available_bikes  weather_id  \
354573      56                     32                8         803   
354574      95                     29               11         801   
354575      24                     13                7         802   
354576       7                     24                5         800   
354577      36                     21               19         802   

       weather_main  main_temp  main_feels_like  main_temp_max  main_temp_min  \
354573       Clouds     279.82           275.91         280.37         279.15   
354574       Clouds     288.63           286.28         290.15         287.15   
354575       Clouds     284.34           277.47         285.15         283.15   
354576        Clear     280.29           276.67         280.93         279.15   
354577       Clouds     284.57           281.16         285.37         282.59   

        main_pressure  main_humidity  wind_speed                dt  \
354573           1016             81        3.60  24/03/2021 03:53   
354574           1023             72        3.60  30/03/2021 15:40   
354575           1006             66        8.23  25/03/2021 17:55   
354576           1015             87        3.60  25/03/2021 00:46   
354577           1030             62        3.09  21/03/2021 15:25   

                   test1  
354573  24/03/2021 04:00  
354574  30/03/2021 15:45  
354575  25/03/2021 18:00  
354576  25/03/2021 00:45  
354577  21/03/2021 15:30

In [14]:
dftrain.head()

number  available_bike_stands  available_bikes  weather_id weather_main  \
1      58                     29               11         803       Clouds   
2      19                     23                7         803       Clouds   
3      61                     18                7         800        Clear   
4      53                     37                3         803       Clouds   
5      98                     40                0         801       Clouds   

   main_temp  main_feels_like  main_temp_max  main_temp_min  main_pressure  \
1     280.78           274.91         281.15         280.15           1034   
2     281.16           278.41         282.04         280.15           1026   
3     280.22           276.22         280.93         278.71           1013   
4     278.85           275.54         279.26         278.15           1032   
5     286.17           285.15         286.48         285.37           1026   

   main_humidity  wind_speed                dt             test1  
1             71        6.17  02/04/2021 12:13  02/04/2021 12:15  
2             76        2.06  22/03/2021 05:29  22/03/2021 05:30  
3             87        4.12  25/03/2021 04:18  25/03/2021 04:15  
4             81        4.63  02/04/2021 07:18  02/04/2021 07:15  
5             62        8.23  04/04/2021 13:35  04/04/2021 13:30

In [15]:
#save updated file for training data on. 
dftrain.to_csv(r'C:\Users\Rache\OneDrive\Documents\comp30670SE\traindatajumbleAnew.csv')

In [16]:
#save updated file for testing model on
dftest.to_csv(r'C:\Users\Rache\OneDrive\Documents\comp30670SE\testdatajumbleAnew.csv')

In [17]:
df=pd.read_csv(r'C:\Users\Rache\OneDrive\Documents\comp30670SE\traindatajumbleAnew.csv')

In [18]:
df.head()

Unnamed: 0  number  available_bike_stands  available_bikes  weather_id  \
0           1      58                     29               11         803   
1           2      19                     23                7         803   
2           3      61                     18                7         800   
3           4      53                     37                3         803   
4           5      98                     40                0         801   

  weather_main  main_temp  main_feels_like  main_temp_max  main_temp_min  \
0       Clouds     280.78           274.91         281.15         280.15   
1       Clouds     281.16           278.41         282.04         280.15   
2        Clear     280.22           276.22         280.93         278.71   
3       Clouds     278.85           275.54         279.26         278.15   
4       Clouds     286.17           285.15         286.48         285.37   

   main_pressure  main_humidity  wind_speed                dt  \
0           1034             71        6.17  02/04/2021 12:13   
1           1026             76        2.06  22/03/2021 05:29   
2           1013             87        4.12  25/03/2021 04:18   
3           1032             81        4.63  02/04/2021 07:18   
4           1026             62        8.23  04/04/2021 13:35   

              test1  
0  02/04/2021 12:15  
1  22/03/2021 05:30  
2  25/03/2021 04:15  
3  02/04/2021 07:15  
4  04/04/2021 13:30

In [19]:
df=df.drop(["Unnamed: 0"],axis=1)

In [20]:
df.head()

number  available_bike_stands  available_bikes  weather_id weather_main  \
0      58                     29               11         803       Clouds   
1      19                     23                7         803       Clouds   
2      61                     18                7         800        Clear   
3      53                     37                3         803       Clouds   
4      98                     40                0         801       Clouds   

   main_temp  main_feels_like  main_temp_max  main_temp_min  main_pressure  \
0     280.78           274.91         281.15         280.15           1034   
1     281.16           278.41         282.04         280.15           1026   
2     280.22           276.22         280.93         278.71           1013   
3     278.85           275.54         279.26         278.15           1032   
4     286.17           285.15         286.48         285.37           1026   

   main_humidity  wind_speed                dt             test1  
0             71        6.17  02/04/2021 12:13  02/04/2021 12:15  
1             76        2.06  22/03/2021 05:29  22/03/2021 05:30  
2             87        4.12  25/03/2021 04:18  25/03/2021 04:15  
3             81        4.63  02/04/2021 07:18  02/04/2021 07:15  
4             62        8.23  04/04/2021 13:35  04/04/2021 13:30

In [21]:
df.dtypes

number                     int64
available_bike_stands      int64
available_bikes            int64
weather_id                 int64
weather_main              object
main_temp                float64
main_feels_like          float64
main_temp_max            float64
main_temp_min            float64
main_pressure              int64
main_humidity              int64
wind_speed               float64
dt                        object
test1                     object
dtype: object

In [22]:
df['weather_main']=df['weather_main'].astype('category')

In [23]:
df['dt']=df['dt'].apply(pd.to_datetime) 

In [24]:
df.dtypes

number                            int64
available_bike_stands             int64
available_bikes                   int64
weather_id                        int64
weather_main                   category
main_temp                       float64
main_feels_like                 float64
main_temp_max                   float64
main_temp_min                   float64
main_pressure                     int64
main_humidity                     int64
wind_speed                      float64
dt                       datetime64[ns]
test1                            object
dtype: object

In [25]:
df=df=df.drop(["test1"],axis=1)

In [26]:
df.head()

number  available_bike_stands  available_bikes  weather_id weather_main  \
0      58                     29               11         803       Clouds   
1      19                     23                7         803       Clouds   
2      61                     18                7         800        Clear   
3      53                     37                3         803       Clouds   
4      98                     40                0         801       Clouds   

   main_temp  main_feels_like  main_temp_max  main_temp_min  main_pressure  \
0     280.78           274.91         281.15         280.15           1034   
1     281.16           278.41         282.04         280.15           1026   
2     280.22           276.22         280.93         278.71           1013   
3     278.85           275.54         279.26         278.15           1032   
4     286.17           285.15         286.48         285.37           1026   

   main_humidity  wind_speed                  dt  
0             71        6.17 2021-02-04 12:13:00  
1             76        2.06 2021-03-22 05:29:00  
2             87        4.12 2021-03-25 04:18:00  
3             81        4.63 2021-02-04 07:18:00  
4             62        8.23 2021-04-04 13:35:00

In [27]:
dups_number=df.pivot_table(index=['number'], aggfunc='size')
len(dups_number)

110

In [28]:
# expect there will be duplicates for a lot of rows no issues in this kind of data as it is expected. 

In [29]:
#checking for Nan values. 
df.isna().sum()

number                   0
available_bike_stands    0
available_bikes          0
weather_id               0
weather_main             0
main_temp                0
main_feels_like          0
main_temp_max            0
main_temp_min            0
main_pressure            0
main_humidity            0
wind_speed               0
dt                       0
dtype: int64

In [30]:
#lookign for constant values - 5 categories total. 
#clounds most common then clear
#drizzle least common. 
df["weather_main"].value_counts() 

Clouds     317063
Clear       20659
Rain        15379
Mist          892
Drizzle       579
Name: weather_main, dtype: int64

In [31]:
df['number'].unique()

array([ 58,  19,  61,  53,  98,  71, 100,  34,  42,  94,  75,  47, 113,
        59,  51,  26,  39,  55,  79,  21,  64,  24,  97,  31,  83,  33,
        41,  96,   5,  74,  32,  25,  73, 101,  68,  13,  82,  36,  80,
       109,  17,  72,  29,  99,  69, 103,  77,   7,  23,  93, 110,  57,
        84,  88,   3,  56,  12,  92,   9, 116,  11,  89,   8,  67,  27,
        76,  87,  44,  86,  30,  15,  43, 117,  85, 106, 112,  22,  18,
        52, 114, 105,  65,  90,  45,  49,  63,  40,  78, 104,  28,  48,
        95,  10,  91, 115,  50,   6,  37, 108, 107,  62,   2,  54, 102,
       111,  66,  38,  16,   4, 507], dtype=int64)

In [32]:
df['weather_id'].unique()

array([803, 800, 801, 501, 802, 500, 804, 701, 300], dtype=int64)

In [33]:
df['main_pressure'].unique()

array([1034, 1026, 1013, 1032, 1020, 1002, 1019, 1018, 1033, 1023, 1024,
        999, 1000, 1004, 1009, 1012, 1015, 1029, 1014, 1030, 1016, 1021,
       1001, 1011, 1017, 1035, 1022, 1028, 1025, 1010, 1006, 1003, 1007,
       1008, 1031, 1036, 1027,  998, 1005,  997], dtype=int64)

In [34]:
df['main_humidity'].unique()

array([ 71,  76,  87,  81,  62,  61,  66,  57,  82,  67,  93,  75,  72,
        77, 100,  80,  70,  86,  58,  63,  88,  65], dtype=int64)

In [35]:
df['wind_speed'].unique()


array([ 6.17,  2.06,  4.12,  4.63,  8.23,  6.69,  3.6 ,  5.66,  3.09,
        2.57,  9.26,  5.14,  1.54,  7.72,  8.75,  7.2 ,  9.77,  1.03,
       10.29, 10.8 , 12.86,  0.51,  0.82, 11.83, 11.32])

In [36]:
df['main_feels_like'].unique()


array([274.91, 278.41, 276.22, ..., 281.86, 272.76, 275.63])